spring.application.name=LinkShortener

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = ${LINKSHORTENER_DATASOURCE_URL}
spring.datasource.username = ${LINKSHORTENER_DATASOURCE_USERNAME}
spring.datasource.password = ${LINKSHORTENER_DATASOURCE_PASSWORD}
